require('./Mongo').connect()
const express = require('express')
const cors = require('cors')
const pupilSignupRoute = require('../Routes/PupilSignup')
const teacherSignupRoute = require('../Routes/TeacherSignup')
const pupilLoginRoute = require('../Routes/PupilLogin')
const teacherLoginRoute = require('../Routes/TeacherLogin')
const getPupilToken = require('../Routes/getPupilToken')
const resetPupilPassword = require('../Routes/resetPupilPassword')
const updatePupilPassword = require('../Routes/updatePupilPassword')


const app = express()
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(cors()) 
app.listen(process.env.PORT)

app.use('/pupilsignup', pupilSignupRoute)
app.use('/teachersignup', teacherSignupRoute)
app.use('/pupillogin', pupilLoginRoute)
app.use('/teacherlogin', teacherLoginRoute)
app.use('/getpupiltoken', getPupilToken)
app.use('/resetpassword', resetPupilPassword)
app.use('/updatepassword', updatePupilPassword)

