require('./Mongo').connect()
const express = require('express')
const cors = require('cors')
const pupilSignupRoute = require('../Routes/PupilSignup')
const teacherSignupRoute = require('../Routes/TeacherSignup')
const pupilLoginRoute = require('../Routes/PupilLogin')
const teacherLoginRoute = require('../Routes/TeacherLogin')
const resetPupilPassword = require('../Routes/resetPupilPassword')
const updatePupilPassword = require('../Routes/updatePupilPassword')
const resetTeacherPassword = require('../Routes/resetTeacherPassword')
const updateTeacherPassword = require('../Routes/updateTeacherPassword')
const getpupiltoken = require('../Routes/getPupilToken')


const app = express()
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(cors()) 
app.listen(process.env.PORT)

app.use('/pupilsignup', pupilSignupRoute)
app.use('/teachersignup', teacherSignupRoute)
app.use('/pupillogin', pupilLoginRoute)
app.use('/teacherlogin', teacherLoginRoute)
app.use('/resetpupilpassword', resetPupilPassword)
app.use('/updatepupilpassword', updatePupilPassword)
app.use('/resetteacherpassword', resetTeacherPassword)
app.use('/updateteacherpassword', updateTeacherPassword)

